version: '3.8'

services:

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dvdrental
    ports:
      - "5432:5432"
    volumes:
      - $PWD/dvdrental:/dvdrental
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
